An approach to implementing CI
lomefin/jedis pull request #1
Opened 2017-03-20 13:33 UTC by vargas-jevd

This is  an initial approach to implementing CI on Jedis project.
In order to achieve this goal, the project has been linked to Travis-CI.
Since Jedis is a JavaScript project, I'm using PhantomJS to orchestrate headless tests.
Basically, what I'm doing is running tests in lib/jedis-test.js with the help of PhantomJS.
The work is still in progress.
Some rework might have to be done on jedis-test.js in order to make CI possible under this approach.
I'm open to any feedback, from a quick pair of eyes on the code, to critique on design and technical approach.

2017-03-20 15:06 UTC, lomefin requested changes
As you can see in the rest of the files, indentation is used with 2 spaces instead of 4.

2017-03-20 15:15 UTC, lomefin requested changes

2017-03-20 15:15 UTC, lomefin commented on testrunner.js
> +			phantom.exit(-1);
If there is an error, maybe it should be printed out.

2017-03-27 21:56 UTC, vargas-jevd commented
Changes requested has been made.
A new version of jedis-test.js was created.
With this new version is now possible to truly test Jedis using Travis-CI.

2017-03-28 00:02 UTC, lomefin approved these changes
Looks good.

2017-03-28 00:02 UTC, merged